# Generated by Django 5.1 on 2024-09-29 04:11

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('muni_id', models.AutoField(primary_key=True, serialize=False)),
                ('muni_name', models.CharField(max_length=100, verbose_name='Municipality Name')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geom')),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('brgy_id', models.AutoField(primary_key=True, serialize=False)),
                ('brgy_name', models.CharField(max_length=100, verbose_name='Barangay Name')),
                ('muni_id', models.ForeignKey(db_column='muni_id', default=9, on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='monitoring.municipality', verbose_name='Municipality Name')),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'unique_together': {('brgy_name', 'muni_id')},
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('birthday', models.DateField(default=datetime.date(2001, 12, 2), verbose_name='Birthday')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20, verbose_name='Sex')),
                ('contactNumber', models.CharField(default='09582488441', max_length=12, validators=[monitoring.models.validate_contact_number], verbose_name='Contact Number')),
                ('brgy_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_brgy', to='monitoring.barangay', verbose_name='Barangay')),
                ('muni_id', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='patients_muni', to='monitoring.municipality', verbose_name='Municipality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Patient Records',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_generic_name', models.CharField(choices=[('PCECCV', 'PCECCV'), ('PVRV', 'PVRV')], max_length=10, verbose_name='Vaccine Generic Name')),
                ('vaccine_brand_name', models.CharField(choices=[('Verorab', 'Verorab'), ('Speeda', 'Speeda'), ('Vaxirab', 'Vaxirab'), ('Abhayrab', 'Abhayrab')], max_length=10, verbose_name='Vaccine Brand Name')),
                ('vaccine_route', models.CharField(choices=[('intramuscular', 'Intramuscular'), ('intradermal', 'Intradermal')], max_length=50, verbose_name='Vaccine Route')),
                ('tcv_given', models.DateField(blank=True, null=True, verbose_name='TCV')),
                ('day0', models.DateField(blank=True, null=True, verbose_name='Day 0')),
                ('day0_arrived', models.BooleanField(default=False, verbose_name='')),
                ('day3', models.DateField(blank=True, null=True, verbose_name='Day 3')),
                ('day3_arrived', models.BooleanField(default=False, verbose_name='')),
                ('day7', models.DateField(blank=True, null=True, verbose_name='Day 7')),
                ('day7_arrived', models.BooleanField(default=False, verbose_name='')),
                ('day14', models.DateField(blank=True, null=True, verbose_name='Day 14')),
                ('day28', models.DateField(blank=True, null=True, verbose_name='Day 28')),
                ('booster1', models.DateField(blank=True, null=True, verbose_name='Booster1')),
                ('booster2', models.DateField(blank=True, null=True, verbose_name='Booster2')),
                ('hrig_given', models.DateField(blank=True, null=True, verbose_name='HRIG')),
                ('rig_given', models.DateField(blank=True, null=True, verbose_name='ERIG')),
                ('animal_alive', models.BooleanField(default=True, null=True, verbose_name='Animal alive')),
                ('remarks', models.TextField(blank=True)),
                ('patient_id', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='treatments_patient', to='monitoring.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name_plural': "Patient's Treatment",
                'ordering': ['-patient_id'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Registration Number')),
                ('date_registered', models.DateField(default=datetime.date(2024, 9, 1), verbose_name='Date Registered')),
                ('date_of_exposure', models.DateField(blank=True, default=datetime.date(2024, 8, 16), null=True, verbose_name='Date of Exposure')),
                ('category_of_exposure', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], default='II', max_length=10, verbose_name='Exposure Category')),
                ('source_of_exposure', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Others', 'Others')], default='Cat', max_length=10, verbose_name='Animal')),
                ('exposure_type', models.CharField(choices=[('Bite', 'Bite'), ('Non-Bite', 'Non-Bite')], default='Bite', max_length=10, verbose_name='Type of Exposure')),
                ('bite_site', models.CharField(default='right thigh', max_length=100, verbose_name='Bite Site')),
                ('provoked_status', models.CharField(choices=[('Provoked', 'Provoked'), ('Unprovoked', 'Unprovoked')], default='Unprovoked', max_length=20, verbose_name='Provocation Status')),
                ('immunization_status', models.CharField(choices=[('Immunized', 'Immunized'), ('Unimmunized', 'Unimmunized')], default='Unimmunized', max_length=20, verbose_name='Animal Vaccination')),
                ('status_of_animal', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Killed', 'Killed'), ('Lost', 'Lost')], default='Lost', max_length=20, verbose_name='Animal Status')),
                ('confinement_status', models.CharField(choices=[('Stray', 'Stray'), ('Leashed/Caged', 'Leashed/Caged')], default='Stray', max_length=20, verbose_name='Confinement Status')),
                ('washing_hands', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, verbose_name='Washing Wound')),
                ('latitude', models.FloatField(blank=True, default=0.0, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, default=0.0, verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Geometry')),
                ('brgy_id', models.ForeignKey(db_column='brgy_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_brgy', to='monitoring.barangay', verbose_name='Barangay Exposure')),
                ('muni_id', models.ForeignKey(db_column='muni_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_muni', to='monitoring.municipality', verbose_name='Municipality of Exposure')),
                ('patient_id', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='monitoring.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name_plural': "Patient's History",
                'ordering': ['-registration_no'],
                'unique_together': {('registration_no', 'patient_id')},
            },
        ),
    ]
