# Generated by Django 5.0.6 on 2024-07-09 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_of_exposure',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 1), null=True, verbose_name='Date of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_registered',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day0',
            field=models.DateField(default=datetime.date(2024, 1, 3), verbose_name='Day 0'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day3',
            field=models.DateField(default=datetime.date(2024, 1, 6), verbose_name='Day 3'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day7',
            field=models.DateField(default=datetime.date(2024, 1, 10), verbose_name='Day 7'),
        ),
    ]
