# Generated by Django 5.1 on 2024-09-15 13:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_history_brgy_id_alter_history_muni_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='muni_id',
            field=models.ForeignKey(db_column='muni_id', default=9, on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='monitoring.municipality', verbose_name='Municipality Name'),
        ),
        migrations.AlterField(
            model_name='history',
            name='brgy_id',
            field=models.ForeignKey(db_column='brgy_id', default=129, on_delete=django.db.models.deletion.CASCADE, related_name='history_brgy', to='monitoring.barangay', verbose_name='Barangay Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_exposure',
            field=models.DateField(blank=True, default=datetime.date(2024, 6, 26), null=True, verbose_name='Date of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_registered',
            field=models.DateField(default=datetime.date(2024, 7, 14), verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='history',
            name='muni_id',
            field=models.ForeignKey(db_column='muni_id', default=9, on_delete=django.db.models.deletion.CASCADE, related_name='history_muni', to='monitoring.municipality', verbose_name='Municipality of Exposure'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='brgy_id',
            field=models.ForeignKey(default=129, on_delete=django.db.models.deletion.CASCADE, related_name='patients_brgy', to='monitoring.barangay', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='muni_id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='patients_muni', to='monitoring.municipality', verbose_name='Municipality'),
        ),
    ]
