# Generated by Django 5.1 on 2024-10-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_history_human_rabies'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='municipality_logo/', verbose_name='Municipality Logo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='brgy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_brgy', to='monitoring.barangay', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='muni_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_muni', to='monitoring.municipality', verbose_name='Municipality'),
        ),
    ]
