# Generated by Django 5.0.6 on 2024-07-16 10:02

import datetime
import django.db.models.deletion
import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_history_date_of_exposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='other_animal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Animal'),
        ),
        migrations.AlterField(
            model_name='history',
            name='brgy_id',
            field=models.ForeignKey(db_column='brgy_id', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='history_brgy', to='monitoring.barangay', verbose_name='Barangay of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_exposure',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 1), null=True, verbose_name='Date of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_registered',
            field=models.DateField(default=datetime.date(2024, 3, 25), verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='history',
            name='muni_id',
            field=models.ForeignKey(db_column='muni_id', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='history_muni', to='monitoring.municipality', verbose_name='Municipality of Exposure'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default=datetime.date(1999, 6, 25), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='brgy_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='patients_brgy', to='monitoring.barangay', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contactNumber',
            field=models.CharField(default='09582488441', max_length=12, validators=[monitoring.models.validate_contact_number], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='muni_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='patients_muni', to='monitoring.municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day0',
            field=models.DateField(default=datetime.date(2024, 1, 6), verbose_name='Day 0'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day3',
            field=models.DateField(default=datetime.date(2024, 1, 10), verbose_name='Day 3'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day7',
            field=models.DateField(default=datetime.date(2024, 1, 13), verbose_name='Day 7'),
        ),
    ]
