# Generated by Django 5.1 on 2024-09-16 05:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_barangay_muni_id_alter_history_brgy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='brgy_id',
            field=models.ForeignKey(db_column='brgy_id', default=11, on_delete=django.db.models.deletion.CASCADE, related_name='history_brgy', to='monitoring.barangay', verbose_name='Barangay Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_exposure',
            field=models.DateField(blank=True, default=datetime.date(2024, 8, 16), null=True, verbose_name='Date of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_registered',
            field=models.DateField(default=datetime.date(2024, 9, 1), verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='history',
            name='muni_id',
            field=models.ForeignKey(db_column='muni_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_muni', to='monitoring.municipality', verbose_name='Municipality of Exposure'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default=datetime.date(2001, 12, 2), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='brgy_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='patients_brgy', to='monitoring.barangay', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='muni_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_muni', to='monitoring.municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day0',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 4), null=True, verbose_name='Day 0'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day3',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 7), null=True, verbose_name='Day 3'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='day7',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 11), null=True, verbose_name='Day 7'),
        ),
    ]
