# Generated by Django 5.1 on 2024-11-12 04:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Geometry'),
        ),
    ]
