# Generated by Django 5.0.6 on 2024-07-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_history_other_animal_alter_history_brgy_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='other_animal',
        ),
        migrations.AlterField(
            model_name='history',
            name='source_of_exposure',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Others', 'Others')], max_length=10, verbose_name='Animal'),
        ),
    ]
