# Generated by Django 5.1 on 2024-10-03 07:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_municipality_logo_alter_patient_brgy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Boundary'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='municipality_logo', verbose_name='Municipality Logo'),
        ),
    ]
