# Generated by Django 5.1 on 2024-10-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_barangay_boundary_alter_municipality_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='logo',
        ),
    ]
