# Generated by Django 5.1 on 2024-09-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_history_brgy_id_alter_history_date_of_exposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='day28_arrived',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
