# Generated by Django 5.0.6 on 2024-07-22 12:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_remove_history_other_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='brgy_id',
            field=models.ForeignKey(db_column='brgy_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_brgy', to='monitoring.barangay', verbose_name='Barangay of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_exposure',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 18), null=True, verbose_name='Date of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_registered',
            field=models.DateField(default=datetime.date(2024, 4, 11), verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='history',
            name='muni_id',
            field=models.ForeignKey(db_column='muni_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_muni', to='monitoring.municipality', verbose_name='Municipality of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='source_of_exposure',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Others', 'Others')], default='Cat', max_length=10, verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='history',
            name='status_of_animal',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Killed', 'Killed'), ('Lost', 'Lost')], default='Lost', max_length=20, verbose_name='Animal Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='brgy_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_brgy', to='monitoring.barangay', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='muni_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_muni', to='monitoring.municipality', verbose_name='Municipality'),
        ),
    ]
