# Generated by Django 5.0.6 on 2024-07-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_history_brgy_id_alter_history_date_of_exposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
