# Generated by Django 5.1 on 2024-10-08 07:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_municipality_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Boundary'),
        ),
        migrations.AlterField(
            model_name='history',
            name='bite_site',
            field=models.CharField(max_length=100, verbose_name='Bite Site'),
        ),
        migrations.AlterField(
            model_name='history',
            name='brgy_id',
            field=models.ForeignKey(db_column='brgy_id', on_delete=django.db.models.deletion.CASCADE, related_name='history_brgy', to='monitoring.barangay', verbose_name='Barangay Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='category_of_exposure',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=10, verbose_name='Exposure Category'),
        ),
        migrations.AlterField(
            model_name='history',
            name='confinement_status',
            field=models.CharField(choices=[('Stray', 'Stray'), ('Leashed/Caged', 'Leashed/Caged')], max_length=20, verbose_name='Confinement Status'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_exposure',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_registered',
            field=models.DateField(verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='history',
            name='exposure_type',
            field=models.CharField(choices=[('Bite', 'Bite'), ('Non-Bite', 'Non-Bite')], max_length=10, verbose_name='Type of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='immunization_status',
            field=models.CharField(choices=[('Immunized', 'Immunized'), ('Unimmunized', 'Unimmunized')], max_length=20, verbose_name='Animal Vaccination'),
        ),
        migrations.AlterField(
            model_name='history',
            name='muni_id',
            field=models.ForeignKey(db_column='muni_id', on_delete=django.db.models.deletion.CASCADE, related_name='history_muni', to='monitoring.municipality', verbose_name='Municipality of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='provoked_status',
            field=models.CharField(choices=[('Provoked', 'Provoked'), ('Unprovoked', 'Unprovoked')], max_length=20, verbose_name='Provocation Status'),
        ),
        migrations.AlterField(
            model_name='history',
            name='source_of_exposure',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Others', 'Others')], max_length=10, verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='history',
            name='status_of_animal',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Killed', 'Killed'), ('Lost', 'Lost')], max_length=20, verbose_name='Animal Status'),
        ),
        migrations.AlterField(
            model_name='history',
            name='washing_hands',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Washing Wound'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contactNumber',
            field=models.CharField(max_length=12, validators=[monitoring.models.validate_contact_number], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, verbose_name='Sex'),
        ),
    ]
