# Generated by Django 5.0.6 on 2024-08-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_municipality_latitude_municipality_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='longitude',
        ),
    ]
