# Generated by Django 5.1 on 2024-11-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_doctor_brgy_id_alter_history_brgy_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors_patient', to='monitoring.doctor', verbose_name='Doctor'),
        ),
    ]
