# Generated by Django 5.1 on 2024-11-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_remove_patient_doctor_treatment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_of_exposure',
            field=models.DateField(null=True, verbose_name='Date of Exposure'),
        ),
    ]
