# Generated by Django 5.0.6 on 2024-08-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_barangay_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='street',
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(default='Zone 4', max_length=100, verbose_name='Street'),
        ),
    ]
