# Generated by Django 5.0.6 on 2024-08-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_remove_barangay_street_patient_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
    ]
