# Generated by Django 5.1 on 2024-11-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_treatment_day0_alter_treatment_day3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='remarks',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Incomplet', 'Incomplet'), ('Died', 'Died'), ('None', 'None')], max_length=100, null=True, verbose_name='Remarks'),
        ),
    ]
