# Generated by Django 5.1 on 2024-11-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_treatment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='remarks',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Incomplete', 'Incomplete'), ('Died', 'Died'), ('None', 'None')], max_length=100, null=True, verbose_name='Remarks'),
        ),
    ]
