# Generated by Django 5.0.6 on 2024-08-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_patient_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='street',
        ),
    ]
