# Generated by Django 5.0.6 on 2024-08-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_remove_patient_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='tmp_muni',
            field=models.CharField(default='Caibiran', max_length=100, verbose_name='Tmp muni'),
        ),
    ]
