# Generated by Django 5.0.6 on 2024-08-23 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_barangay_tmp_muni'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_exposure',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 1), null=True, verbose_name='Date of Exposure'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_registered',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Date Registered'),
        ),
    ]
