# Generated by Django 5.0.6 on 2024-08-23 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_remove_barangay_latitude_remove_barangay_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geometry'),
        ),
    ]
